import { ILanguage } from "./interfaces";

export const SupportedLanguages: ILanguage[] = [
    {
        name: 'Arabic',
        key: 'ar-EG',
        rtl: true,
        sourceLanguage: true,
        supportedUserLocale: false,
    },
    {
        name: 'Chinese (Simplified)',
        key: 'zh-Hans',
        rtl: false,
        sourceLanguage: true,
        supportedUserLocale: true,
    },
    {
        name: 'English',
        key: 'en-US',
        rtl: false,
        sourceLanguage: true,
        supportedUserLocale: true,
    },
    {
        name: 'French',
        key: 'fr-FR',
        rtl: false,
        sourceLanguage: true,
        supportedUserLocale: true,
    },
    {
        name: 'German',
        key: 'de-DE',
        rtl: false,
        sourceLanguage: true,
        supportedUserLocale: true,
    },
    {
        name: 'Italian',
        key: 'it-IT',
        rtl: false,
        sourceLanguage: true,
        supportedUserLocale: true,
    },
    {
        name: 'Japanese',
        key: 'ja-JP',
        rtl: false,
        sourceLanguage: true,
        supportedUserLocale: true,
    },
    {
        name: 'Portuguese',
        key: 'pt-BR',
        rtl: false,
        sourceLanguage: true,
        supportedUserLocale: true,
    },
    {
        name: 'Russian',
        key: 'ru-RU',
        rtl: false,
        sourceLanguage: true,
        supportedUserLocale: true,
    },
    {
        name: 'Spanish',
        key: 'es-ES',
        rtl: false,
        sourceLanguage: true,
        supportedUserLocale: true,
    },
    {
        name: 'Filipino',
        key: 'fil-PH',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Afrikaans',
        key: 'Af-ZA',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Bangla',
        key: 'Bn-BD',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Bosnian',
        key: 'Bs-Latn',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Bulgarian',
        key: 'Bg-BG',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Catalan',
        key: 'Ca-ES',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Croatian',
        key: 'Hr-HR',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Czech',
        key: 'Cs-CZ',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: true,
    },
    {
        name: 'Danish',
        key: 'Da-DK',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Dutch',
        key: 'Nl-NL',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: true,
    },
    {
        name: 'Fijian',
        key: 'En-FJ',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Samoan',
        key: 'En-WS',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Estonian',
        key: 'Et-EE',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Finnish',
        key: 'Fi-FI',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Greek',
        key: 'El-GR',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Haitian',
        key: 'Fr-HT',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Hebrew',
        key: 'He-IL',
        rtl: true,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Hindi',
        key: 'Hi-IN',
        rtl: false,
        sourceLanguage: true,
        supportedUserLocale: true,
    },
    {
        name: 'Hungarian',
        key: 'Hu-HU',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: true,
    },
    {
        name: 'Indonesian',
        key: 'Id-ID',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Kiswahili',
        key: 'Sw-KE',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Korean',
        key: 'Ko-KR',
        rtl: false,
        sourceLanguage: true,
        supportedUserLocale: true,
    },
    {
        name: 'Latvian',
        key: 'Lv-LV',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Lithuanian',
        key: 'Lt-LT',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Malagasy',
        key: 'Mg-MG',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Malay',
        key: 'Ms-MY',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Maltese',
        key: 'Mt-MT',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Norwegian',
        key: 'Nb-NO',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Persian',
        key: 'Fa-IR',
        rtl: true,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Polish',
        key: 'Pl-PL',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: true,
    },
    {
        name: 'Romanian',
        key: 'Ro-RO',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Serbian (Cyrillic)',
        key: 'Sr-Cyrl-RS',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Serbian (Latin)',
        key: 'Sr-Latn-RS',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Slovak',
        key: 'Sk-SK',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Slovenian',
        key: 'Sl-SI',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Swedish',
        key: 'Sv-SE',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: true,
    },
    {
        name: 'Tamil',
        key: 'Ta-IN',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Thai',
        key: 'Th-TH',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Tongan',
        key: 'To-TO',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Turkish',
        key: 'Tr-TR',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: true,
    },
    {
        name: 'Ukrainian',
        key: 'Uk-UA',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Urdu',
        key: 'Ur-PK',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Vietnamese',
        key: 'Vi-VN',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    },
    {
        name: 'Chinese (Traditional)',
        key: 'Zh-Hant',
        rtl: false,
        sourceLanguage: false,
        supportedUserLocale: false,
    }
];
